project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd

format:
  html:
    self-contained: true
    theme: cosmo
    css: styles.css
    toc: true

resources:
  - "figures/*"



